### ISSUE TITLE
[Bug] `Warning: Each child in a list should have a unique "key" prop.`

### ISSUE THREAD

**Issue by Zerohertz** [Zerohertz/about-v1#20]
리스트 항목에 고유한 "key" 속성을 사용하는 것과 관련하여 경고 메시지가 나타나고 있습니다.
이 경고는 CommonDescription, CommonRows, ProjectRow 등 여러 컴포넌트에서 발생하고 있습니다.

```node
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <ul>. See https://reactjs.org/link/warning-keys for more information.
    at CommonDescription (webpack-internal:///./component/common/CommonDescription.tsx:15:3)
    at div
    at Col (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Col.js:57:25)
    at div
    at Row (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Row.js:42:25)
    at div
    at CommonRows (webpack-internal:///./component/common/CommonRow.tsx:17:3)
    at div
    at Col (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Col.js:57:25)
    at div
    at Row (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Row.js:42:25)
    at EmptyRowCol (webpack-internal:///./component/common/index.tsx:14:3)
    at ProjectRow (webpack-internal:///./component/project/row.tsx:19:3)
    at div
    at Col (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Col.js:57:25)
    at div
    at Row (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Row.js:42:25)
    at EmptyRowCol (webpack-internal:///./component/common/index.tsx:14:3)
    at div
    at CommonSection (webpack-internal:///./component/common/CommonSection.tsx:17:3)
    at Component (webpack-internal:///./component/project/index.tsx:17:5)
    at div
    at Container (/home/zerohertz/Zerohertz/about/node_modules/reactstrap/lib/Container.js:31:25)
    at Yosume
    at YosumeApp (webpack-internal:///./pages/_app.tsx:31:3)
    at StyleRegistry (/home/zerohertz/Zerohertz/about/node_modules/next/dist/styled-jsx/dist/index/index.js:671:34)
    at AppContainer (/home/zerohertz/Zerohertz/about/node_modules/next/dist/server/render.js:280:29)
    at AppContainerWithIsomorphicFiberStructure (/home/zerohertz/Zerohertz/about/node_modules/next/dist/server/render.js:309:57)
    at div
    at Body (/home/zerohertz/Zerohertz/about/node_modules/next/dist/server/render.js:596:21)
```

| 컴포넌트 이름         | 경로 및 파일                                         | 경고 위치 (줄 번호) |
|--------------------|--------------------------------------------------|------------------|
| CommonDescription  | `component/common/CommonDescription.tsx`         | 15               |
| Col                | `node_modules/reactstrap/lib/Col.js`             | 57               |
| Row                | `node_modules/reactstrap/lib/Row.js`             | 42               |
| CommonRows         | `component/common/CommonRow.tsx`                 | 17               |
| EmptyRowCol        | `component/common/index.tsx`                     | 14               |
| ProjectRow         | `component/project/row.tsx`                      | 19               |
| CommonSection      | `component/common/CommonSection.tsx`             | 17               |
| Component          | `component/project/index.tsx`                    | 17               |
| Container          | `node_modules/reactstrap/lib/Container.js`       | 31               |
| YosumeApp          | `pages/_app.tsx`                                 | 31               |
| StyleRegistry      | `node_modules/next/dist/styled-jsx/dist/index.js` | 671              |
| AppContainer       | `node_modules/next/dist/server/render.js`        | 280              |
| AppContainerWithIsomorphicFiberStructure | `node_modules/next/dist/server/render.js` | 309              |
| Body               | `node_modules/next/dist/server/render.js`        | 596              |

**Comment by Zerohertz** [comment]
> FMI: https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key
